# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

VCFtogeno <- function(vcf) {
    .Call(`_gpart_VCFtogeno`, vcf)
}

pairCubeX <- function(b1, b2) {
    .Call(`_gpart_pairCubeX`, b1, b2)
}

matCubeX <- function(geno) {
    .Call(`_gpart_matCubeX`, geno)
}

matCubeX2 <- function(geno1, geno2) {
    .Call(`_gpart_matCubeX2`, geno1, geno2)
}

estiD <- function(pA, pB, n11, n12, n21, n22, n1212) {
    .Call(`_gpart_estiD`, pA, pB, n11, n12, n21, n22, n1212)
}

CIDp <- function(b1, b2) {
    .Call(`_gpart_CIDp`, b1, b2)
}

genoDp <- function(geno, strLD = TRUE, lower = 0.7, upper = 0.98) {
    .Call(`_gpart_genoDp`, geno, strLD, lower, upper)
}

genoDp2 <- function(geno1, geno2, strLD = TRUE, lower = 0.7, upper = 0.98) {
    .Call(`_gpart_genoDp2`, geno1, geno2, strLD, lower, upper)
}

genoCubeDp <- function(geno) {
    .Call(`_gpart_genoCubeDp`, geno)
}

